# Generated by Django 4.2.4 on 2023-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
