# Generated by Django 4.2.4 on 2023-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_user_info', 'Can view user info'), ('view_group_inof', 'Can view group info'), ('view_permission', 'Can view permission'), ('view_content_type', 'Can view content type'), ('view_session', 'Can view session'), ('view_message', 'Can view message'), ('view_logentry', 'Can view log entry'), ('view_book', 'Can view book'), ('view_author', 'Can view author'), ('view_publisher', 'Can view publisher'), ('view_category', 'Can view category'), ('view_comment', 'Can view comment'), ('view_bookinstance', 'Can view bookinstance'), ('view_genre', 'Can view genre'), ('view_language', 'Can view language')),
                'managed': False,
            },
        ),
    ]
