# Generated by Django 4.2.4 on 2023-08-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
