# Generated by Django 4.2.4 on 2023-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
